---
abstract: 'A directory tree widget for wxPerl'
author:
  - 'Renee Baecker <module@renee-baecker.de>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.102340, CPAN::Meta::Converter version 2.102160'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Wx-Perl-DirTree
requires:
  Cwd: 0
  Exporter: 0
  File::Spec: 0
  Test::More: 0
  Wx::Perl::VirtualTreeCtrl: 1.017
version: 0.07
